[package]
name = "majority-element-ii"
version = "0.1.0"
authors = ["Inside <inside@insidezhou.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
