[package]
name = "path-in-zigzag-labelled-binary-tree"
version = "0.1.0"
authors = ["Inside <inside@insidezhou.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.1.42"
log = "0.4.14"
env_logger = "0.9.0"