security:
    keyFile: /etc/mongo-keyFile

net:
    bindIp: 0.0.0.0
    port: 27019

storage:
    dbPath: /var/lib/mongodb
    journal:
        enabled: true

systemLog:
    logAppend: true

sharding:
    clusterRole: configsvr

replication:
    replSetName: configRS
