#!/bin/sh


basedir=$(cd `dirname $0`; pwd)
parentdir=$(cd $basedir; cd ..; pwd)
hostname=$(hostname)

mkdir -p /var/lib/mongodb/router
chmod -R 777 /var/lib/mongodb/router

docker run --name mongodb-router \
	--restart=always \
	--log-opt max-size=1g \
	--network=host \
	-d \
	-v $parentdir/hosts:/etc/hosts \
	-v $basedir/mongod-router.yml:/etc/mongod.yml \
	-v /var/lib/mongodb/router:/var/lib/mongodb \
	example/mongo \
	mongos --config /etc/mongod.yml
