#!/bin/sh


basedir=$(cd `dirname $0`; pwd)
parentdir=$(cd $basedir; cd ..; pwd)
hostname=$(hostname)

mkdir -p /var/lib/mongodb/config
chmod -R 777 /var/lib/mongodb/config

docker run --name mongodb-config \
	--restart=always \
	--log-opt max-size=1g \
	--network=host \
	-d \
	-v $parentdir/hosts:/etc/hosts \
	-v $basedir/mongod-config.yml:/etc/mongod.yml \
	-v /var/lib/mongodb/config:/var/lib/mongodb \
	example/mongo \
	mongod --config /etc/mongod.yml
