#!/bin/sh


basedir=$(cd `dirname $0`; pwd)
parentdir=$(cd $basedir; cd ..; pwd)
hostname=$(hostname) 

if [ ! -n "$1" ];then
    echo -e "\n第一个参数需要指定html目录的位置，绝对路径"
    exit 1
fi

docker run --name openresty \
	--network=host \
	--restart=always \
	-d \
	-v /var/log/openresty:/usr/local/openresty/nginx/logs \
	-v $basedir/conf:/usr/local/openresty/nginx/conf \
	-v $1:/usr/local/openresty/nginx/html \
	inside/openresty