#!/bin/sh


basedir=$(cd `dirname $0`; pwd)
parentdir=$(cd $basedir; cd ..; pwd)
hostname=$(hostname) 

if [ ! -n "$1" ];then
    echo -e "\n第一个参数需要指定log的max-size"
    exit 1
fi

docker run --name openresty \
	--log-opt max-size=$1 \
	--network=host \
	--restart=always \
	-d \
	-v $basedir/conf:/usr/local/openresty/nginx/conf \
	-v $basedir/html:/usr/local/openresty/nginx/html \
	inside/openresty