#!/bin/sh


basedir=$(cd `dirname $0`; pwd)
parentdir=$(cd $basedir; cd ..; pwd)
hostname=$(hostname)

mkdir -p /var/lib/redis
mkdir -p /var/log/redis

chmod -R 777 /var/lib/redis
chmod -R 777 /var/log/redis

docker run --name redis \
	--restart=always \
	--network=host \
	-d \
	-v $parentdir/hosts:/etc/hosts \
	-v $basedir/redis.conf:/etc/redis/redis.conf \
	-v /var/lib/redis:/var/lib/redis \
	-v /var/log/redis:/var/log/redis \
	redis:5 \
	redis-server /etc/redis/redis.conf
